#+TITLE: Jokes


* Technology jokes:

  Gigahertz: When the rock bands lead singer swan dives from the stage but no
  one catches him.

  Megabyte: When your mouth overrides your ability to keep your job slinging
  hamburgers.

  Hard Drive: That trip you make to the in-laws every Sunday for dinner!

  Microwave: When you lift one finger off the steering wheel to wave.

  Keyboard: The main structural backbone in ship building.

  Algorithms: Highly trained dancing alligators.

  Semi-Conductor: Person in training to lead an orchestra.

  Terabyte: When a pitbull latches on to the seat of your pants but you emerge
  unscathed.

  C++ code language: When you earned a B but your college professor doesn't like
  your pink hair.

  Blue Tooth: When a lack of brushing goes way beyond the yellow tooth stage.

* Cute jokes:

  What does homework stand for?
  Half of my energy wasted on random knowledge.

  Why did the dog sit in the shade?
  Because he didn't want to be a hot dog.

  Where do hamburgers dance?
  At a meat ball.

  What did the paper say to the pencil?
  You've got a really good point.

  What kind of cup can't you drink out of?
  A cup-cake.

* Knock knock jokes:

  Knock, knock
  Who’s there?
  Merry.
  Merry who?
  Merry Christmas!

  Knock, knock.
  Who’s there?
  Harry.
  Harry who?
  Harry up, it’s cold out here!

  Knock, knock.
  Who’s there?
  Noah.
  Noah who?
  Noah good place we can get something to eat?

  Knock, knock.
  Who’s there?
  Annie.
  Annie who?
  Annie body home?
  Knock, knock.
  Who's there?
  Broccoli.
  Broccoli who?
  Broccoli doesn't have a last name, silly.

* Christmas jokes:

  What happens to elves when they behave naughty?
  Santa gives them the sack.

  What kind of music do elves listen to?
  Wrap.

  What is a snowmans favorite breakfast?
  Ice Crispies.

  Why didn't the Skeleton go to the Christmas party?
  He had no-body to go with.

  Who hides in the bakery at Christmas?
  A Mince Spy!


* Dad jokes:

  Dad, can you put my shoes on?
  No, I don't think they'll fit me.

  Dad, did you get a haircut?
  No I got them all cut.

  Want to hear a joke about construction?
  I'm still working on it.

  Why couldn't the bicycle stand up by itself?
  It was two tired.

  Dad, can you put the cat out?
  I didn't know it was on fire.
